name: Create Index Files

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Index Builder
        run: node firebase/tools/create-index.js

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add firebase/_data/index.yml firebase/_data/index.json
          git commit -m "Update library/vault index" || echo "No changes"
          git push
